name: checkout实例

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 选择项目
      run: |
        # 不能用let index=RANDOM % 4
        # 如果右值是0，那么let的退出码就是1，bash就直接终止了。
        index=$((RANDOM % 4))
        arr=(github-actions-demo advanced-play-search uMatrixCleaner)
        targetRepo=${arr[index]}
        if [[ ${targetRepo} ]]; then
          echo "将会检出${targetRepo}"
          echo "::set-env name=targetRepo::$targetRepo"
        else
          echo "没有选中任何项目"
        fi
    - name: 检出项目
      if: ${{ env.targetRepo }}
      uses: actions/checkout@v2.1.0
      with:
        repository: gqqnbig/${{ env.targetRepo }}
        path: targetRepo
    - name: 检查日志
      if: ${{ env.targetRepo }}
      run: |
        cd ${GITHUB_WORKSPACE}/targetRepo
        git log -1
