name: 高级求职

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: 设置shell环境变量
      run: |
        x=1
        y=2
        let z=x+y
        echo "::set-env name=z::$z"
    - name: 条件执行1
      if: env.z > 2
      run: |
        echo $z
    - name: 条件执行2
      if: env.z > 3
      run: |
        echo $z